import SEO from "@/components/site/SEO";
import SectionHeader from "@/components/site/SectionHeader";
import { images } from "@/data/siteContent";

export default function About() {
  return (
    <>
      <SEO title="Über uns | Autoreinigung Zürich-Nord" description="Seit 2020 reinigt das 5-köpfige Team von Autoreinigung Zürich-Nord Fahrzeuge mit Herz, Hand und professioneller Fahrzeugpflege." path="/ueber-uns" image={images.about} />
      <section className="px-5 py-20 lg:px-8"><div className="mx-auto grid max-w-7xl items-center gap-12 lg:grid-cols-2"><div><p className="mb-5 text-xs font-extrabold uppercase tracking-[0.28em] text-primary">Über uns</p><h1 className="font-heading text-5xl font-extrabold tracking-tight md:text-7xl">Handarbeit, Erfahrung, echte Resultate</h1><p className="mt-7 text-lg leading-8 text-muted-foreground">Seit 2020 reinigen wir Fahrzeuge in Zürich-Schwamendingen – von Hand, mit hochwertigen Mitteln und mit dem Anspruch, dass Sie Ihr Auto danach wirklich wiedererkennen. Unser 5-köpfiges Team ist Teil der Kfz-Werkstatt turicum-automobile.ch und pflegt Fahrzeuge mit der gleichen Sorgfalt, die man von einem guten Mechaniker erwartet: gründlich, ehrlich und ohne unnötigen Aufwand.</p></div><img src={images.about} alt="Eingangsbereich Zürich Nord Autoreinigung" className="rounded-[2.5rem] shadow-2xl" /></div></section>
      <section className="bg-secondary/70 px-5 py-20 lg:px-8"><div className="mx-auto max-w-4xl"><SectionHeader eyebrow="Fahrzeugwert" title="Gepflegt ist mehr wert – das gilt für jedes Fahrzeug." /><div className="mt-8 space-y-5 text-lg leading-8 text-muted-foreground"><p>Eine professionelle Aufbereitung zahlt sich aus – nicht nur optisch, sondern auch finanziell. Ein sauberes, gepflegtes Fahrzeug erzielt beim Verkauf erfahrungsgemäss mehrere hundert Franken mehr. Kauf- und Leasinginteressenten urteilen zuerst über das Erscheinungsbild – und wer gepflegt ist, wirkt gepflegt.</p><p>Das gilt auch umgekehrt: Sie haben eine Occasion mit Gebrauchsspuren gekauft und möchten sie aufwerten? Eine Aufbereitung kostet einen Bruchteil einer Neulackierung – und das Ergebnis überrascht oft beide Seiten. Auch für Oldtimer und Classic Cars ist regelmässige Pflege wichtig, damit Material und Patina erhalten bleiben.</p><p>Haben Sie Fragen oder möchten Sie ein Angebot für Ihr Fahrzeug? Rufen Sie uns an oder buchen Sie direkt online – wir schauen es uns gerne an.</p></div></div></section>
    </>
  );
}