import SEO from "@/components/site/SEO";

export default function Impressum() {
  return (
    <>
      <SEO title="Impressum | Autoreinigung Zürich-Nord" description="Impressum der Autoreinigung Zürich-Nord, Heerenwiesen 18, 8051 Zürich." path="/impressum" />
      <section className="px-5 py-20 lg:px-8"><article className="prose prose-slate mx-auto max-w-4xl rounded-[2rem] border border-border bg-card p-8 shadow-xl md:p-12"><h1>Impressum</h1><h2>Verantwortlich für den Inhalt der Seiten</h2><p><strong>Autoreinigung Zürich-Nord</strong><br />Heerenwiesen 18<br />8051 Zürich</p><p><a href="mailto:info@autoreinigung-zuerich-nord.ch">info@autoreinigung-zuerich-nord.ch</a></p><p>Telefon: <a href="tel:+41445119490">+41 44 511 94 90</a></p><p>MWST-Nr. CHE-329.889.425 MWST<br />Handelsreg. Nr. CH-020.4.068.035-4</p><h2>Disclaimer</h2><p>Alle Texte und Links wurden sorgfältig geprüft und werden laufend aktualisiert. Wir sind bemüht, richtige und vollständige Informationen auf dieser Website bereitzustellen, übernehmen aber keinerlei Verantwortung, Garantien oder Haftung dafür, dass die durch diese Website bereitgestellten Informationen, richtig, vollständig oder aktuell sind. Wir behalten uns das Recht vor, jederzeit und ohne Vorankündigung die Informationen auf dieser Website zu ändern und verpflichten uns auch nicht, die enthaltenen Informationen zu aktualisieren.</p><p>Alle Links zu externen Anbietern wurden zum Zeitpunkt ihrer Aufnahme auf ihre Richtigkeit überprüft, dennoch haften wir nicht für Inhalte und Verfügbarkeit von Websites, die mittels Hyperlinks zu erreichen sind.</p><h2>Datenschutz</h2><p>Für die Sicherheit der Datenübertragung im Internet können wir keine Gewähr übernehmen, insbesondere besteht bei der Übertragung von Daten per E-Mail die Gefahr des Zugriffs durch Dritte.</p><p>Einer Nutzung der im Impressum veröffentlichten Kontaktdaten durch Dritte zu Werbezwecken wird hiermit ausdrücklich widersprochen.</p><h2>Google Analytics</h2><p>Diese Website benutzt Google Analytics, einen Webanalysedienst der Google Inc. („Google“). Google Analytics verwendet sog. „Cookies“, Textdateien, die auf Ihrem Computer gespeichert werden und die eine Analyse der Benutzung der Website durch Sie ermöglichen.</p></article></section>
    </>
  );
}