name: Build and Deploy to Infomaniak (Production Live)

on:
  push:
    branches:
      - production

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 24
        cache: 'npm'

    - name: Install Dependencies and Build App
      run: |
        npm ci
        npm run build

    - name: SCP Deploy Production Files via SSH
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.AUTOREINIGUNG_INFOMANIAK_HOST }}
        username: ${{ secrets.AUTOREINIGUNG_INFOMANIAK_USERNAME }}
        password: ${{ secrets.AUTOREINIGUNG_INFOMANIAK_PASSWORD }}
        port: 22
        source: 'dist/*'
        target: 'sites/meisterflow.autoreinigung-zuerich-nord.ch/'
        strip_components: 1

        # added integration google tag manager and klaviyo!!
        # Updated all of the CTA with the new Calenso provided by the client.

