name: Build and Deploy to Hostpoint

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: 'npm'

    - name: Install Dependencies and Build App
      run: |
        npm ci
        npm run build

    - name: SFTP Deploy Production Files
      uses: wlixcc/SFTP-Deploy-Action@v1.2.4
      with:
        username: 'gazazoze'
        server: 'sl2679.web.hostpoint.ch'
        port: 22
        ssh_private_key: ${{ secrets.HOSTPOINT_SSH_KEY }}
        # This tells it to only upload the freshly compiled build output folder:
        local_path: './dist/*'
        remote_path: '/www/autoreinigung.meisterflow.ch/'